services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./data/ny_taxi_2020:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_COOKIE_SECRET=53tegevd66efdvfff
    ports:
      - "8080:80"
  # runjob:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
